### ISSUE TITLE
Help me about loading bar in mxstbr/react-boilerplate

### ISSUE THREAD

**Issue by iioollun** [mironov/react-redux-loading-bar#22]
I used react-redux-loading-bar in mxstbr/react-boilerplate and maybe i wrong in config. Can you help me?? 
- I added <LoadingBar /> at root app
- I added "loadingBar: loadingBarReducer" in root reducer (in combineReducers).
And it's not working.. May I miss or something??

**Comment by mironov** [comment]
Hey @iioollun, it seems that `react-boilerplate` comes with its own ProgressBar: https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/progressbar.md

In order to use `react-redux-loading-bar` with `react-boilerplate` you will have to remove the progress bar wrapper and use the immutable version. Here's a quick demo of the changes needed: https://github.com/mironov/react-boilerplate/commit/4a2888acafe3fd210794506c78709a0bf4ceebd0

Please feel free to reopen the issue if that doesn't work for you.
